### ISSUE TITLE
好像有个小错误

### ISSUE THREAD

**Issue by shecairui** [Evian-Zhang/llvm-ir-tutorial#1]
%stack_variable = alloca i32
%1 = add i32 1, 2
store i32 %1, i32* %stack_variable
%2 = add i32 3, 4
store i32 %1, i32* %stack_variable
为什么最后一行是%1，我觉得好像是2%。
很感谢作者的教程，学到很多

**Comment by Evian-Zhang** [comment]
是个笔误，已修改。谢谢！
