### ISSUE TITLE
Section 4. 类型系统：级联访问 貌似有个typo

### ISSUE THREAD

**Issue by Scarlett-HS** [Evian-Zhang/llvm-ir-tutorial#13]
[Section 4. 类型系统：级联访问](https://evian-zhang.github.io/llvm-ir-tutorial/04-%E7%B1%BB%E5%9E%8B%E7%B3%BB%E7%BB%9F.html#%E7%BA%A7%E8%81%94%E8%AE%BF%E9%97%AE)
@Evian-Zhang 
![微信图片_20240127233100](https://github.com/Evian-Zhang/llvm-ir-tutorial/assets/88608721/be5b0b7b-ed08-4e81-bcce-40ed12201147)

**Comment by Evian-Zhang** [comment]
感谢指正:)
