### ISSUE TITLE
opt --O3 优化级别

### ISSUE THREAD

**Issue by jjeejj** [Evian-Zhang/llvm-ir-tutorial#2]
LLVM后端优化IR 使用 `opt`
这里的优化级别参数为 **--O3**, 不是 **-O3**
![image](https://user-images.githubusercontent.com/15176971/97098421-b49dd180-16b7-11eb-8632-005c6a3eb5ac.png)

clang 的 是 **-O3**

**Comment by Evian-Zhang** [comment]
多谢。已修改
