### ISSUE TITLE
GEP指令的例子似乎有问题

### ISSUE THREAD

**Issue by duchao713** [Evian-Zhang/llvm-ir-tutorial#3]
第四章，对于getelementptr的讲解，
`%MyStruct = type {
i32,
i32
}
%my_structs = alloca [4 x %MyStruct]
%1 = getelementptr [4 x %MyStruct], [4 x %MyStruct]* %my_structs, i64 2,
i32 1 ; %1 is pointer to my_structs[2].y
%2 = load i32, i32* %1 ; %2 is value of my_structs[2].y`

这里，似乎少了一个索引0? 应该是%1 = getelementptr [4 x %MyStruct], [4 x %MyStruct]* %my_structs, i64 0, i64 2,
i32 1

**Comment by Evian-Zhang** [comment]
确实目前写的是错误的。我最近暂时没空修改，过几天会看看。如果您方便的话，欢迎提PR。
