### ISSUE TITLE
opt test.ll -S --O3 不会生效

### ISSUE THREAD

**Issue by ZhenlanJi** [Evian-Zhang/llvm-ir-tutorial#4]
LLVM IR入门指南(1)中`clang -S -emit-llvm test.c` 生成的.ll文件中带有`attributes #0 = { optnone ......}`，这会导致opt跳过该函数，即`opt test.ll -S --O3`输出结果与test.ll相比较不会有任何改动。

已知的解决办法是直接删去该属性，想请教一下是否可以在使用clang生成IR文件时通过某个特定命令行参数直接禁止掉这个属性？

**Comment by Evian-Zhang** [comment]
已修改，谢谢！
