### ISSUE TITLE
是否會繼續更新更多內容 / Will this tutorial update for more contents

### ISSUE THREAD

**Issue by Luminous-Coder** [Evian-Zhang/llvm-ir-tutorial#5]
寫得很好，想請問未來還會不會更新更多內容，會這麼問是因為這個儲存庫已經有一小段時間沒有動靜了。

Nice tutorial!! Will it update for more contents in the future? I asked this because of the quiet of the repository.

**Comment by Evian-Zhang** [comment]
谢谢您。

目前暂时没有主动更新的计划，但如果有issue指出问题，或是提出有价值的pr，会进行及时的修改。
